<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Comun\Comun.csproj" />
    <ProjectReference Include="..\Dominio\Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Casos\Abogados asignados\FrmAgregarAbogadoAsistente.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Abogados asignados\FrmAgregarSocioResponsable.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Abogados asignados\FrmAgregarAbogadoDirector.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Estados\FrmAgregarEstadoLaboralTerminado.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Estados\FrmAgregarEstadoLaboralPIR.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Estados\FrmAgregarEstadoLaboralSI.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Laborales\Laboral_terminados.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Laborales\Laboral_segunda_instancia.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Laborales\Laboral_primer_instancia_recursos_resolucion.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Laborales\Laboral_primer_instancia.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Participantes\FrmAgregarContactoEmpresa.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Participantes\FrmAgregarTerceroInteresado.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Casos\Participantes\FrmAgregarDemandante.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Personas\ContactoEmpresa.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Personas\TercerosInteresados.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Personas\Demandantes.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Personas\Demandados.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Casos\Civiles\" />
  </ItemGroup>

</Project>